version: "3.8"

services:
    postgres:
        image: pgvector/pgvector:pg16
        container_name: ai_planner_postgres
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./app/db/init.sql:/docker-entrypoint-initdb.d/init.sql
        restart: unless-stopped
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}",
                ]
            interval: 30s
            timeout: 10s
            retries: 3

    minio:
        image: minio/minio:latest
        container_name: ai_planner_minio
        ports:
            - "9000:9000"
            - "9001:9001"
        environment:
            MINIO_ROOT_USER: ${MINIO_ROOT_USER}
            MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
            # Event notification 설정 (생성 및 삭제 이벤트)
            MINIO_NOTIFY_WEBHOOK_ENABLE_pdf_processor: "on"
            MINIO_NOTIFY_WEBHOOK_ENDPOINT_pdf_processor: "http://app:8000/api/v1/minio/webhook"
        volumes:
            - minio_data:/data
        command: server /data --console-address ":9001"
        restart: unless-stopped
        healthcheck:
            test:
                ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
            interval: 30s
            timeout: 20s
            retries: 3

    app:
        build: .
        container_name: ai_planner_app
        ports:
            - "8000:8000"
        environment:
            - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
            - OLLAMA_BASE_URL=http://host.docker.internal:11434
            - MINIO_ENDPOINT=minio:9000
            - MINIO_ACCESS_KEY=${MINIO_ROOT_USER}
            - MINIO_SECRET_KEY=${MINIO_ROOT_PASSWORD}
            - MINIO_BUCKET=pdf-documents
            - MINIO_SECURE=false
        depends_on:
            postgres:
                condition: service_healthy
            minio:
                condition: service_healthy
        restart: unless-stopped
        extra_hosts:
            - "host.docker.internal:host-gateway"

volumes:
    postgres_data:
    minio_data:
